Feature: Geonames Wikipedia FullText Search
  Webservice Type : XML or JSON
  Url : api.geonames.org/wikipediaSearch?
  api.geonames.org/wikipediaSearchJSON?
  Parameters : q : place name (urlencoded utf8)
  title : search in the wikipedia title (optional)
  lang : language code, supported languages are de,en,es,fr,it,nl,pl,pt,ru,zh (default = en)
  maxRows : maximal number of rows returned (default = 10)
  Result : returns the wikipedia entries found for the searchterm as xml document
  Example http://api.geonames.org/wikipediaSearch?q=london&maxRows=10&username=demo

  Scenario Outline: Pequannock
    Given I am testing on the fake web service
    When I search for wikipedia articles mentioning "Pequannock"
    Then I should find "20" articles
    And I should be able to verify title="<title>", feature="<feature>", fact1="<fact1>", fact2="<fact2>", fact3="<fact3>", fact4="<fact4>"

    Examples:
      |title                                |feature |fact1                                                                       |fact2                                                          |fact3                                                                   |fact4                                                                        |
      |Pequannock Township, New Jersey      |city    |township in Morris County, New Jersey                                       |2010 United States Census, the township's population was 15,420|13,888 counted in the 2000 Census                                       |                                                                             |
      |Kinnelon, New Jersey                 |city    |borough in Morris County, New Jersey                                        |2010 United States Census, the borough's population was 10,248 |9,365 counted in the 2000 Census                                        |                                                                             |
      |Pequannock River                     |river   |tributary of the Pompton River                                              |approximately 20 miles (32 km) long                            |located in northern New Jersey                                          |It rises in eastern Sussex County                                            |
      |Rockaway Township, New Jersey        |city    |township in Morris County, New Jersey                                       |2010 United States Census, the township's population was 24,156|22,930 counted in the 2000 Census                                       |                                                                             |
      |Pequannock Township School District  |edu     |comprehensive community public school district                              |serves students in Kindergarten through twelfth grade          |                                                                        |                                                                             |
      |Pequannock Township High School      |edu     |established in 1956                                                         |four-year comprehensive public high school                     |students in ninth through twelfth grades from Pequannock Township       |operating as the lone secondary school of the Pequannock Township School     |
      |West Milford, New Jersey             |city    |township in Passaic County, New Jersey                                      |2010 United States Census, the township's population was 25,850|26,410 counted in the 2000 Census                                       |                                                                             |
      |Pompton River                        |river   |tributary of the Passaic River                                              |approximately 8 mi (13 km) long                                |formed south of the borough of Pompton Lakes                            |confluence of the Ramapo and Pequannock rivers                               |
      |Morris County, New Jersey            |adm2nd  |located in the U.S. state of New Jersey                                     |about west of New York City                                    |2010 United States Census, the population was 492,276                   |                                                                             |
      |Wayne, New Jersey                    |city    |township in Passaic County, New Jersey                                      |located less than from Midtown Manhattan                       |2010 United States Census, the township had a total population of 54,717|                                                                             |
      |Butler, New Jersey                   |city    |borough in Morris County, New Jersey                                        |2010 United States Census, the borough's population was 7,539  |7,420 counted in the 2000 Census                                        |                                                                             |
      |Hardyston Township, New Jersey       |city    |is a township in Sussex County, New Jersey                                  |2010 United States Census, the township's population was 8,213 |6,171 counted in the 2000 Census                                        |                                                                             |
      |Jefferson Township, New Jersey       |city    |the northernmost township in Morris County                                  |Beautiful Jefferson Township                                   |nestled deep in the northwest corner of Morris County, New Jersey       |countryside town                                                             |
      |Highland Lakes, New Jersey           |city    |mistakenly referred to as Highland Lake by the United States Census Bureau  |CDP name changes: Highland Lake previously Highland Lakes      |                                                                        |                                                                             |
      |Boonton, New Jersey                  |city    |town in Morris County                                                       |2010 United States Census, the town's population was 8,347     |8,496 counted in the 2000 Census                                        |                                                                             |
      |Roman Catholic Diocese of Paterson   |landmark|diocese of the Latin Rite of the Roman Catholic Church in the United States |includes three counties in northern New Jersey:                |Passaic, Morris, and Sussex                                             |third-largest in the state of New Jersey                                     |
      |Riverdale, New Jersey                |city    |borough in Morris County, New Jersey                                        |2010 United States Census, the borough's population was 3,559  |2,498 counted in the 2000 Census                                        |                                                                             |
      |Vernon Township, New Jersey          |city    |township in Sussex County, New Jersey                                       |about one hour's drive from New York City                      |part of the New York Metropolitan Area                                  |2010 United States Census, the township's population was 23,943              |
      |Lincoln Park, New Jersey             |city    |borough in Morris County, New Jersey                                        |2010 United States Census, the borough's population was 10,521 |10,930 counted in the 2000 Census                                       |                                                                             |
      |Montville, New Jersey                |city    |township in Morris County, New Jersey                                       |2010 United States Census, the township's population was 21,528|20,839 counted in the 2000 Census                                       |                                                                             |

  Scenario Outline: Pequannock
    Given I am testing on the actual web service
    When I search for wikipedia articles mentioning "Pequannock"
    Then I should find "20" articles
    And I should be able to verify title="<title>", feature="<feature>", fact1="<fact1>", fact2="<fact2>", fact3="<fact3>", fact4="<fact4>"

    Examples:
      |title                                |feature |fact1                                                                       |fact2                                                          |fact3                                                                   |fact4                                                                        |
      |Pequannock Township, New Jersey      |city    |township in Morris County, New Jersey                                       |2010 United States Census, the township's population was 15,420|13,888 counted in the 2000 Census                                       |                                                                             |
      |Kinnelon, New Jersey                 |city    |borough in Morris County, New Jersey                                        |2010 United States Census, the borough's population was 10,248 |9,365 counted in the 2000 Census                                        |                                                                             |
      |Pequannock River                     |river   |tributary of the Pompton River                                              |approximately 20 miles (32 km) long                            |located in northern New Jersey                                          |It rises in eastern Sussex County                                            |
      |Rockaway Township, New Jersey        |city    |township in Morris County, New Jersey                                       |2010 United States Census, the township's population was 24,156|22,930 counted in the 2000 Census                                       |                                                                             |
      |Pequannock Township School District  |edu     |comprehensive community public school district                              |serves students in Kindergarten through twelfth grade          |                                                                        |                                                                             |
      |Pequannock Township High School      |edu     |established in 1956                                                         |four-year comprehensive public high school                     |students in ninth through twelfth grades from Pequannock Township       |operating as the lone secondary school of the Pequannock Township School     |
      |West Milford, New Jersey             |city    |township in Passaic County, New Jersey                                      |2010 United States Census, the township's population was 25,850|26,410 counted in the 2000 Census                                       |                                                                             |
      |Pompton River                        |river   |tributary of the Passaic River                                              |approximately 8 mi (13 km) long                                |formed south of the borough of Pompton Lakes                            |confluence of the Ramapo and Pequannock rivers                               |
      |Morris County, New Jersey            |adm2nd  |located in the U.S. state of New Jersey                                     |about west of New York City                                    |2010 United States Census, the population was 492,276                   |                                                                             |
      |Wayne, New Jersey                    |city    |township in Passaic County, New Jersey                                      |located less than from Midtown Manhattan                       |2010 United States Census, the township had a total population of 54,717|                                                                             |
      |Butler, New Jersey                   |city    |borough in Morris County, New Jersey                                        |2010 United States Census, the borough's population was 7,539  |7,420 counted in the 2000 Census                                        |                                                                             |
      |Hardyston Township, New Jersey       |city    |is a township in Sussex County, New Jersey                                  |2010 United States Census, the township's population was 8,213 |6,171 counted in the 2000 Census                                        |                                                                             |
      |Jefferson Township, New Jersey       |city    |the northernmost township in Morris County                                  |Beautiful Jefferson Township                                   |nestled deep in the northwest corner of Morris County, New Jersey       |countryside town                                                             |
      |Highland Lakes, New Jersey           |city    |mistakenly referred to as Highland Lake by the United States Census Bureau  |CDP name changes: Highland Lake previously Highland Lakes      |                                                                        |                                                                             |
      |Boonton, New Jersey                  |city    |town in Morris County                                                       |2010 United States Census, the town's population was 8,347     |8,496 counted in the 2000 Census                                        |                                                                             |
      |Roman Catholic Diocese of Paterson   |landmark|diocese of the Latin Rite of the Roman Catholic Church in the United States |includes three counties in northern New Jersey:                |Passaic, Morris, and Sussex                                             |third-largest in the state of New Jersey                                     |
      |Riverdale, New Jersey                |city    |borough in Morris County, New Jersey                                        |2010 United States Census, the borough's population was 3,559  |2,498 counted in the 2000 Census                                        |                                                                             |
      |Vernon Township, New Jersey          |city    |township in Sussex County, New Jersey                                       |about one hour's drive from New York City                      |part of the New York Metropolitan Area                                  |2010 United States Census, the township's population was 23,943              |
      |Lincoln Park, New Jersey             |city    |borough in Morris County, New Jersey                                        |2010 United States Census, the borough's population was 10,521 |10,930 counted in the 2000 Census                                       |                                                                             |
      |Montville, New Jersey                |city    |township in Morris County, New Jersey                                       |2010 United States Census, the township's population was 21,528|20,839 counted in the 2000 Census                                       |                                                                             |
